/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Update Profile */
        put: operations["update_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_profile_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates */
        get: operations["templates_api_resume_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seed */
        get: operations["seed_api_resume_seed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/materials/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_resume_materials_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/essay-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Essay Sets */
        get: operations["essay_sets_api_resume_essay_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/essay-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Essay Draft */
        post: operations["essay_draft_api_resume_essay_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_resume_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_resume_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render */
        post: operations["render_api_resume_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Form */
        post: operations["convert_form_api_forms_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Award */
        Award: {
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Date */
            date: string;
        };
        /** Body_extract_api_resume_materials_extract_post */
        Body_extract_api_resume_materials_extract_post: {
            /** File */
            file: string;
        };
        /** Body_upload_resume_api_profile_resume_post */
        Body_upload_resume_api_profile_resume_post: {
            /** File */
            file: string;
        };
        /** Career */
        Career: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** Certificate */
        Certificate: {
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            /** Date */
            date: string;
        };
        /**
         * Density
         * @enum {string}
         */
        Density: "compact" | "normal" | "relaxed";
        /** Education */
        Education: {
            /** School */
            school: string;
            /** Major */
            major: string;
            /** Period */
            period: string;
            /** Status */
            status: string;
            /** Gpa */
            gpa: string;
            /**
             * Admission
             * @default
             */
            admission: string;
            /**
             * Graduation
             * @default
             */
            graduation: string;
            /**
             * Degree
             * @default
             */
            degree: string;
        };
        /**
         * FontScale
         * @enum {string}
         */
        FontScale: "S" | "M" | "L";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadingStyle
         * @enum {string}
         */
        HeadingStyle: "plain" | "bar" | "underline";
        /** Job */
        Job: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
            /** Description */
            description: string;
            /** Responsibilities */
            responsibilities: string[];
            /** Requirements */
            requirements: string[];
            /** Preferred */
            preferred: string[];
            /** Company Info */
            company_info: string;
            match_analysis: components["schemas"]["MatchAnalysis"];
        };
        /** JobFeed */
        JobFeed: {
            /** Role */
            role: string;
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** Language */
        Language: {
            /** Language */
            language: string;
            /** Test */
            test: string;
            /** Score */
            score: string;
            /** Date */
            date: string;
        };
        /** Link */
        Link: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** MatchAnalysis */
        MatchAnalysis: {
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
        };
        /** Notification */
        Notification: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Time */
            time: string;
            /** Unread */
            unread: boolean;
        };
        /** Personal */
        Personal: {
            /** Photo */
            photo: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Name Cn */
            name_cn: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Emergency Phone */
            emergency_phone: string;
            /** Emergency Relation */
            emergency_relation: string;
            /**
             * Birth
             * @default
             */
            birth: string;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Military Status
             * @default
             */
            military_status: string;
            /**
             * Military Branch
             * @default
             */
            military_branch: string;
            /**
             * Military Period
             * @default
             */
            military_period: string;
            /**
             * Veteran
             * @default
             */
            veteran: string;
            /**
             * Discharge
             * @default
             */
            discharge: string;
        };
        /** Profile */
        Profile: {
            /** Registered */
            registered: boolean;
            personal: components["schemas"]["Personal"];
            /** Links */
            links: components["schemas"]["Link"][];
            /** Educations */
            educations: components["schemas"]["Education"][];
            /** Languages */
            languages: components["schemas"]["Language"][];
            /** Awards */
            awards: components["schemas"]["Award"][];
            /** Certificates */
            certificates: components["schemas"]["Certificate"][];
            /** Careers */
            careers: components["schemas"]["Career"][];
            /** Projects */
            projects: components["schemas"]["Project"][];
            /** Activities */
            activities: components["schemas"]["ProfileActivity"][];
        };
        /** ProfileActivity */
        ProfileActivity: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Period */
            period: string;
            /** Description */
            description: string;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Summary */
            summary: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** ResumeChatRequest */
        ResumeChatRequest: {
            state: components["schemas"]["ResumeState"];
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["ResumeMaterial"][];
            /** Message */
            message: string;
        };
        /** ResumeChatResponse */
        ResumeChatResponse: {
            state: components["schemas"]["ResumeState"];
            /** Reply */
            reply: string;
        };
        /** ResumeDoc */
        ResumeDoc: {
            header: components["schemas"]["ResumeHeader"];
            /**
             * @default {
             *       "photo": "",
             *       "email": "",
             *       "phone": "",
             *       "address": "",
             *       "birth": "",
             *       "nationality": "",
             *       "military_status": "",
             *       "military_branch": "",
             *       "military_period": "",
             *       "veteran": "",
             *       "discharge": ""
             *     }
             */
            personal: components["schemas"]["ResumePersonal"];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ResumeSection"][];
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Essays
             * @default []
             */
            essays: components["schemas"]["ResumeEssay"][];
            /**
             * Include Essays
             * @default true
             */
            include_essays: boolean;
        };
        /** ResumeEssay */
        ResumeEssay: {
            /** Question */
            question: string;
            /**
             * Answer
             * @default
             */
            answer: string;
            /** Char Limit */
            char_limit?: number | null;
        };
        /** ResumeEssayDraftRequest */
        ResumeEssayDraftRequest: {
            /** Company */
            company: string;
            /** Question */
            question: string;
            /** Char Limit */
            char_limit?: number | null;
            state: components["schemas"]["ResumeState"];
        };
        /** ResumeEssayDraftResponse */
        ResumeEssayDraftResponse: {
            /** Draft */
            draft: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ResumeEssayQuestion */
        ResumeEssayQuestion: {
            /** Id */
            id: number;
            /** Tag */
            tag: string;
            /** Prompt */
            prompt: string;
            /** Char Limit */
            char_limit?: number | null;
        };
        /** ResumeEssaySet */
        ResumeEssaySet: {
            /** Company */
            company: string;
            /**
             * Deadline
             * @default
             */
            deadline: string;
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["ResumeEssayQuestion"][];
        };
        /** ResumeExtractResponse */
        ResumeExtractResponse: {
            /** Text */
            text: string;
        };
        /** ResumeHeader */
        ResumeHeader: {
            /** Name */
            name: string;
            /**
             * Contact
             * @default []
             */
            contact: string[];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["ResumeLink"][];
        };
        /** ResumeLink */
        ResumeLink: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** ResumeMaterial */
        ResumeMaterial: {
            /** Kind */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Text */
            text: string;
        };
        /** ResumePersonal */
        ResumePersonal: {
            /**
             * Photo
             * @default
             */
            photo: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Birth
             * @default
             */
            birth: string;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Military Status
             * @default
             */
            military_status: string;
            /**
             * Military Branch
             * @default
             */
            military_branch: string;
            /**
             * Military Period
             * @default
             */
            military_period: string;
            /**
             * Veteran
             * @default
             */
            veteran: string;
            /**
             * Discharge
             * @default
             */
            discharge: string;
        };
        /** ResumeRenderRequest */
        ResumeRenderRequest: {
            state: components["schemas"]["ResumeState"];
        };
        /** ResumeSection */
        ResumeSection: {
            /** Id */
            id: string;
            type: components["schemas"]["SectionType"];
            /** Title */
            title: string;
            /** Order */
            order: number;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
            /**
             * Items
             * @default []
             */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** ResumeState */
        ResumeState: {
            doc: components["schemas"]["ResumeDoc"];
            /**
             * @default {
             *       "template": "classic",
             *       "font": "Pretendard",
             *       "accent_color": "#334155",
             *       "density": "normal",
             *       "heading_style": "bar",
             *       "font_scale": "M"
             *     }
             */
            style: components["schemas"]["ResumeStyle"];
        };
        /** ResumeStyle */
        ResumeStyle: {
            /**
             * Template
             * @default classic
             */
            template: string;
            /**
             * Font
             * @default Pretendard
             */
            font: string;
            /**
             * Accent Color
             * @default #334155
             */
            accent_color: string;
            /** @default normal */
            density: components["schemas"]["Density"];
            /** @default bar */
            heading_style: components["schemas"]["HeadingStyle"];
            /** @default M */
            font_scale: components["schemas"]["FontScale"];
        };
        /** ResumeTemplate */
        ResumeTemplate: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @default resume
             */
            kind: string;
            /** Thumbnail */
            thumbnail: string;
            preset: components["schemas"]["ResumeStyle"];
        };
        /** ResumeUploadResponse */
        ResumeUploadResponse: {
            profile: components["schemas"]["Profile"];
            /** Parsed Fields */
            parsed_fields: number;
            /** Message */
            message: string;
        };
        /**
         * SectionType
         * @enum {string}
         */
        SectionType: "career" | "project" | "education" | "skill" | "award" | "certificate" | "language" | "activity" | "custom";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                role?: string;
                experience?: string;
                employment?: string;
                location?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    update_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_profile_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_profile_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    templates_api_resume_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeTemplate"][];
                };
            };
        };
    };
    seed_api_resume_seed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeState"];
                };
            };
        };
    };
    extract_api_resume_materials_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_api_resume_materials_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    essay_sets_api_resume_essay_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeEssaySet"][];
                };
            };
        };
    };
    essay_draft_api_resume_essay_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeEssayDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeEssayDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_resume_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_resume_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_api_resume_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    convert_form_api_forms_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
