/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_profile_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Company */
        post: operations["analyze_company_api_companies_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_essays_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Draft */
        post: operations["generate_draft_api_essays_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/questions/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Answer */
        put: operations["save_answer_api_essays_questions__question_id__answer_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Form */
        post: operations["convert_form_api_forms_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Organizer */
            organizer: string;
            /** Period */
            period: string;
            /** Dday */
            dday: string;
            /** Fit */
            fit: number;
            /** Fills Gap */
            fills_gap: string[];
            /** Expected Experience */
            expected_experience: string;
            /** Connections */
            connections: components["schemas"]["Connection"][];
        };
        /** AnswerSlot */
        AnswerSlot: {
            /** Company */
            company: string;
            /** Deadline */
            deadline: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Status
             * @default 미작성
             * @enum {string}
             */
            status: "미작성" | "작성 중" | "초안 완료";
        };
        /** AnswerUpdate */
        AnswerUpdate: {
            /** Company */
            company: string;
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "미작성" | "작성 중" | "초안 완료";
        };
        /** Award */
        Award: {
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Date */
            date: string;
        };
        /** Career */
        Career: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** Certificate */
        Certificate: {
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            /** Date */
            date: string;
        };
        /** CompanyAnalyzeRequest */
        CompanyAnalyzeRequest: {
            /** Name */
            name: string;
        };
        /** CompanyBrief */
        CompanyBrief: {
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Summary */
            summary: string;
            /** Stage */
            stage: string;
            /** Business Areas */
            business_areas: string[];
            /** Products */
            products: string[];
            /** Jd Skills */
            jd_skills: string[];
            /** Signals */
            signals: components["schemas"]["Signal"][];
            /** Strength Matching */
            strength_matching: components["schemas"]["StrengthMatch"][];
            /** Interview Points */
            interview_points: components["schemas"]["InterviewPoint"][];
            /** Apply Tips */
            apply_tips: string[];
        };
        /** Connection */
        Connection: {
            /** Company */
            company: string;
            /** Role */
            role: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Question Id */
            question_id: number;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Question Id */
            question_id: number;
            /** Draft */
            draft: string;
        };
        /** Education */
        Education: {
            /** School */
            school: string;
            /** Major */
            major: string;
            /** Period */
            period: string;
            /** Status */
            status: string;
            /** Gpa */
            gpa: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewPoint */
        InterviewPoint: {
            /** Question */
            question: string;
            /** Hint */
            hint: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
            /** Description */
            description: string;
            /** Responsibilities */
            responsibilities: string[];
            /** Requirements */
            requirements: string[];
            /** Preferred */
            preferred: string[];
            /** Company Info */
            company_info: string;
            match_analysis: components["schemas"]["MatchAnalysis"];
        };
        /** JobFeed */
        JobFeed: {
            /** Role */
            role: string;
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** Language */
        Language: {
            /** Language */
            language: string;
            /** Test */
            test: string;
            /** Score */
            score: string;
            /** Date */
            date: string;
        };
        /** Link */
        Link: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** MatchAnalysis */
        MatchAnalysis: {
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
        };
        /** Notification */
        Notification: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Time */
            time: string;
            /** Unread */
            unread: boolean;
        };
        /** Personal */
        Personal: {
            /** Photo */
            photo: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Name Cn */
            name_cn: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Emergency Phone */
            emergency_phone: string;
            /** Emergency Relation */
            emergency_relation: string;
        };
        /** Profile */
        Profile: {
            /** Registered */
            registered: boolean;
            personal: components["schemas"]["Personal"];
            /** Links */
            links: components["schemas"]["Link"][];
            /** Educations */
            educations: components["schemas"]["Education"][];
            /** Languages */
            languages: components["schemas"]["Language"][];
            /** Awards */
            awards: components["schemas"]["Award"][];
            /** Certificates */
            certificates: components["schemas"]["Certificate"][];
            /** Careers */
            careers: components["schemas"]["Career"][];
            /** Projects */
            projects: components["schemas"]["Project"][];
            /** Activities */
            activities: components["schemas"]["ProfileActivity"][];
        };
        /** ProfileActivity */
        ProfileActivity: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Period */
            period: string;
            /** Description */
            description: string;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Summary */
            summary: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** Question */
        Question: {
            /** Id */
            id: number;
            /** Tag */
            tag: string;
            /** Prompt */
            prompt: string;
            /** Char Limit */
            char_limit: number;
            /** Slots */
            slots: components["schemas"]["AnswerSlot"][];
        };
        /** Signal */
        Signal: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Source */
            source: string;
        };
        /** StrengthMatch */
        StrengthMatch: {
            /** Company Issue */
            company_issue: string;
            /** My Experience */
            my_experience: string;
            /** Fit */
            fit: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                role?: string;
                experience?: string;
                employment?: string;
                location?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    upload_resume_api_profile_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_company_api_companies_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyBrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_essays_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
        };
    };
    generate_draft_api_essays_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_answer_api_essays_questions__question_id__answer_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    convert_form_api_forms_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
