/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Update Profile */
        put: operations["update_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_profile_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Company */
        post: operations["analyze_company_api_companies_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{normalized_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__normalized_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{normalized_name}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Company */
        post: operations["refresh_company_api_companies__normalized_name__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{normalized_name}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_companies__normalized_name__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{normalized_name}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jobs */
        get: operations["get_jobs_api_companies__normalized_name__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{normalized_name}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matches */
        get: operations["get_matches_api_companies__normalized_name__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_essays_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Draft */
        post: operations["generate_draft_api_essays_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/essays/questions/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Answer */
        put: operations["save_answer_api_essays_questions__question_id__answer_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Form */
        post: operations["convert_form_api_forms_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Organizer */
            organizer: string;
            /** Period */
            period: string;
            /** Dday */
            dday: string;
            /** Fit */
            fit: number;
            /** Fills Gap */
            fills_gap: string[];
            /** Expected Experience */
            expected_experience: string;
            /** Connections */
            connections: components["schemas"]["Connection"][];
        };
        /** AnalysisJobStatus */
        AnalysisJobStatus: {
            /** Normalized Name */
            normalized_name: string;
            status: components["schemas"]["AnalysisStatus"];
            /** Warnings */
            warnings: string[];
            /** Last Analyzed At */
            last_analyzed_at: string | null;
        };
        /**
         * AnalysisStatus
         * @description 단계별 상태 — 수집 실패를 전체 실패로 만들지 않는다(계획서 §4).
         * @enum {string}
         */
        AnalysisStatus: "queued" | "collecting" | "analyzing" | "ready" | "partial" | "failed";
        /** AnswerSlot */
        AnswerSlot: {
            /** Company */
            company: string;
            /** Deadline */
            deadline: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Status
             * @default 미작성
             * @enum {string}
             */
            status: "미작성" | "작성 중" | "초안 완료";
        };
        /** AnswerUpdate */
        AnswerUpdate: {
            /** Company */
            company: string;
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "미작성" | "작성 중" | "초안 완료";
        };
        /** Award */
        Award: {
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Date */
            date: string;
        };
        /** Body_upload_resume_api_profile_resume_post */
        Body_upload_resume_api_profile_resume_post: {
            /** File */
            file: string;
        };
        /** Career */
        Career: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** Certificate */
        Certificate: {
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            /** Date */
            date: string;
        };
        /** CompanyAnalyzeRequest */
        CompanyAnalyzeRequest: {
            /** Name */
            name: string;
            /** Job Url */
            job_url?: string | null;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /** CompanyIntelligence */
        CompanyIntelligence: {
            /** Name */
            name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Domain */
            domain: string;
            summary: components["schemas"]["SourcedText"] | null;
            stage: components["schemas"]["SourcedText"] | null;
            /** Business Areas */
            business_areas: components["schemas"]["SourcedText"][];
            /** Products */
            products: components["schemas"]["SourcedText"][];
            /** Signals */
            signals: components["schemas"]["IntelligenceSignal"][];
            /** Jobs */
            jobs: components["schemas"]["CompanyJob"][];
            /** Sources */
            sources: components["schemas"]["SourceSummary"][];
            /** Source Count */
            source_count: number;
            /** Manual Urls */
            manual_urls: string[];
            status: components["schemas"]["AnalysisStatus"];
            /** Warnings */
            warnings: string[];
            /** Needs Review */
            needs_review: string[];
            /** Last Analyzed At */
            last_analyzed_at: string | null;
            /** Fresh Until */
            fresh_until: string | null;
            /** Is Stale */
            is_stale: boolean;
        };
        /**
         * CompanyJob
         * @description 공고/JD 구조화 결과. 모든 항목이 원문 공고(source_id) 하나에서 나온다.
         */
        CompanyJob: {
            /** Id */
            id: number;
            /** Source Id */
            source_id: number;
            /** Title */
            title: string;
            /** Role Category */
            role_category: string;
            /** Location */
            location: string;
            /** Employment */
            employment: string;
            /** Deadline */
            deadline: string;
            /** Description */
            description: string;
            /** Requirements */
            requirements: string[];
            /** Preferred */
            preferred: string[];
            /** Core Skills */
            core_skills: string[];
            /** Problem Types */
            problem_types: string[];
        };
        /**
         * CompanyMatch
         * @description 기업 요구 → 내 경험 → 근거. 점수보다 설명이 먼저다(계획서 §8).
         */
        CompanyMatch: {
            /** Job Id */
            job_id: number | null;
            /** Company Need */
            company_need: string;
            /** Profile Evidence */
            profile_evidence: string;
            match_type: components["schemas"]["MatchType"];
            /** Score */
            score: number;
            /** Reason */
            reason: string;
            /** Source Ids */
            source_ids: number[];
        };
        /** Connection */
        Connection: {
            /** Company */
            company: string;
            /** Role */
            role: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Question Id */
            question_id: number;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Question Id */
            question_id: number;
            /** Draft */
            draft: string;
        };
        /** Education */
        Education: {
            /** School */
            school: string;
            /** Major */
            major: string;
            /** Period */
            period: string;
            /** Status */
            status: string;
            /** Gpa */
            gpa: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntelligenceSignal */
        IntelligenceSignal: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            signal_type: components["schemas"]["SignalType"];
            /** Confidence */
            confidence: number;
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Source Ids */
            source_ids: number[];
        };
        /** Job */
        Job: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Domain */
            domain: string;
            /** Conditions */
            conditions: string;
            /** Title */
            title: string;
            /** Tags */
            tags: string[];
            /** Dday */
            dday: string;
            /** Source */
            source: string;
            /** Match Rate */
            match_rate: number;
            /** Match Reason */
            match_reason: string;
            /** Description */
            description: string;
            /** Responsibilities */
            responsibilities: string[];
            /** Requirements */
            requirements: string[];
            /** Preferred */
            preferred: string[];
            /** Company Info */
            company_info: string;
            match_analysis: components["schemas"]["MatchAnalysis"];
        };
        /** JobFeed */
        JobFeed: {
            /** Role */
            role: string;
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** Language */
        Language: {
            /** Language */
            language: string;
            /** Test */
            test: string;
            /** Score */
            score: string;
            /** Date */
            date: string;
        };
        /** Link */
        Link: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** MatchAnalysis */
        MatchAnalysis: {
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
        };
        /**
         * MatchType
         * @enum {string}
         */
        MatchType: "strength" | "gap" | "question";
        /** Notification */
        Notification: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Message */
            message: string;
            /** Time */
            time: string;
            /** Unread */
            unread: boolean;
        };
        /** Personal */
        Personal: {
            /** Photo */
            photo: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Name Cn */
            name_cn: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Emergency Phone */
            emergency_phone: string;
            /** Emergency Relation */
            emergency_relation: string;
        };
        /** Profile */
        Profile: {
            /** Registered */
            registered: boolean;
            personal: components["schemas"]["Personal"];
            /** Links */
            links: components["schemas"]["Link"][];
            /** Educations */
            educations: components["schemas"]["Education"][];
            /** Languages */
            languages: components["schemas"]["Language"][];
            /** Awards */
            awards: components["schemas"]["Award"][];
            /** Certificates */
            certificates: components["schemas"]["Certificate"][];
            /** Careers */
            careers: components["schemas"]["Career"][];
            /** Projects */
            projects: components["schemas"]["Project"][];
            /** Activities */
            activities: components["schemas"]["ProfileActivity"][];
        };
        /** ProfileActivity */
        ProfileActivity: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Org */
            org: string;
            /** Period */
            period: string;
            /** Description */
            description: string;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Period */
            period: string;
            /** Summary */
            summary: string;
            /** Highlights */
            highlights: string[];
            /** Stack */
            stack: string[];
        };
        /** Question */
        Question: {
            /** Id */
            id: number;
            /** Tag */
            tag: string;
            /** Prompt */
            prompt: string;
            /** Char Limit */
            char_limit: number | null;
            /** Slots */
            slots: components["schemas"]["AnswerSlot"][];
        };
        /** ResumeUploadResponse */
        ResumeUploadResponse: {
            profile: components["schemas"]["Profile"];
            /** Parsed Fields */
            parsed_fields: number;
            /** Message */
            message: string;
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "business" | "product" | "hiring" | "technology" | "risk" | "culture";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "official_site" | "careers" | "dart" | "newsroom" | "job_posting" | "user_url";
        /** SourceSummary */
        SourceSummary: {
            /** Id */
            id: number;
            kind: components["schemas"]["SourceKind"];
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Published At */
            published_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            trust_level: components["schemas"]["TrustLevel"];
            /** Changed */
            changed: boolean;
        };
        /**
         * SourcedText
         * @description 근거를 달고 다니는 사실 한 조각. source_ids가 비면 저장하지 않는다(계획서 §6.4).
         *
         *     요약·규모·사업 영역·제품 — 모든 사실 필드가 이 형태다. 평범한 str로 두면
         *     "근거 없는 문장"이 조용히 섞여 들어온다.
         */
        SourcedText: {
            /** Text */
            text: string;
            /** Source Ids */
            source_ids: number[];
        };
        /**
         * TrustLevel
         * @enum {string}
         */
        TrustLevel: "primary" | "secondary" | "user_provided";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                role?: string;
                experience?: string;
                employment?: string;
                location?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    update_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_profile_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_profile_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_company_api_companies_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyIntelligence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__normalized_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                normalized_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyIntelligence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_company_api_companies__normalized_name__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                normalized_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_companies__normalized_name__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                normalized_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jobs_api_companies__normalized_name__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                normalized_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matches_api_companies__normalized_name__matches_get: {
        parameters: {
            query?: {
                job_id?: number | null;
            };
            header?: never;
            path: {
                normalized_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_essays_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
        };
    };
    generate_draft_api_essays_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_answer_api_essays_questions__question_id__answer_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    convert_form_api_forms_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
